// GENERATED by AI-Agent-Coconala-Factory. Bundles src/ into build/Code.js for Apps Script.
//
// Apps Script has no module loader, so everything is bundled into one IIFE. The Apps Script
// editor only finds functions declared at the true top level of the file, so the footer below
// adds real top-level wrappers that forward to the implementations src/index.ts put on
// globalThis (the same fix used in apps/site-report, see docs/reusable-assets-audit.md).
import { build } from "esbuild";
import { copyFileSync, mkdirSync } from "node:fs";

const footer = `
function doGet(e) {
  return globalThis.__factory_doGet(e);
}
function doPost(e) {
  return globalThis.__factory_doPost(e);
}
function setupSpreadsheet(e) {
  return globalThis.__factory_setupSpreadsheet(e);
}
function setupRichMenu(e) {
  return globalThis.__factory_setupRichMenu(e);
}
`;

await build({
  entryPoints: ["src/index.ts"],
  bundle: true,
  outfile: "build/Code.js",
  target: "es2019",
  format: "iife",
  platform: "neutral",
  footer: { js: footer },
  logLevel: "warning",
});
mkdirSync("build", { recursive: true });
copyFileSync("appsscript.json", "build/appsscript.json");
