import type { IndustryProfile } from "../agents/industrySpecialist";
import type { WorkflowPlan } from "../agents/workflowPlanner";
import type { ClientBrief } from "../schemas/brief";
import type { TraceContext } from "./meta";
import { FACTORY_VERSION } from "./meta";
import type { LineRichMenuConfig } from "./richMenuConfig";
import type { ProjectSchema } from "./spreadsheetSchema";

/**
 * Client-facing documents. They are written in plain Japanese for a
 * non-technical owner (same tone as apps/hair-salon-portfolio/docs/owner-guide.md).
 */

export interface DeliveryInputs {
  brief: ClientBrief;
  profile: IndustryProfile;
  plan: WorkflowPlan;
  schema: ProjectSchema;
  configSeed: Record<string, string>;
  menuConfig: LineRichMenuConfig;
  trace: TraceContext;
  artifacts: string[];
}

const footer = (trace: TraceContext) =>
  `\n---\n\n<sub>Generated by AI-Agent-Coconala-Factory ${FACTORY_VERSION} for ${trace.project} (${trace.industry}; ${trace.workflows.join(", ")}).</sub>\n`;

export function businessRequirementsMd(brief: ClientBrief, trace: TraceContext): string {
  return `# ご要望まとめ — ${brief.project.clientName}

- 業種: ${brief.industry}${brief.businessType ? `（${brief.businessType}）` : ""}
- ブランド名: ${brief.brand.name}${brief.brand.tone ? `／トーン: ${brief.brand.tone}` : ""}

## お客様にできるようにしたいこと

${brief.requirements.length > 0 ? brief.requirements.map((r) => `- ${r}`).join("\n") : "- （記載なし。業種の標準構成を使用）"}

## 既にお持ちのもの

${brief.existingResources.length > 0 ? brief.existingResources.map((r) => `- ${r}`).join("\n") : "- （記載なし）"}
${footer(trace)}`;
}

export function setupMd(input: DeliveryInputs): string {
  const { brief, schema, plan, trace } = input;
  const hasReservation = plan.selected.some((w) => w.id.startsWith("reservation-"));
  // Owner-curated data sheets have an `active` column. Wording stays domain-neutral: no sheet names, not every business has a menu.
  const hasDataSheets = schema.sheets.some((s) => s.columns.some((c) => c.name === "active"));
  const missingRequired = schema.configKeys.filter((k) => k.required && !(k.key in input.configSeed) && k.default === undefined).map((k) => k.key);
  const buttons = input.menuConfig.areas.map((a) => a.action.label).join(" / ");

  return `# セットアップ手順 — ${brief.project.clientName}

この手順書は、LINE リッチメニューと Google スプレッドシートを使った自動受付の初期設定をまとめたものです。
作業時間の目安: 60〜90分（リッチメニュー画像の作成を除く）。

## 0. 事前に用意するもの

- LINE 公式アカウント（Messaging API を有効化済み）
- Google アカウント（スプレッドシートと Apps Script を作成するアカウント）
- リッチメニュー画像（\`rich-menu/design-spec.json\` の仕様どおり ${input.menuConfig.size.width}×${input.menuConfig.size.height}px、1MB 以下）

## 1. スプレッドシートを作る

1. Google ドライブで新しいスプレッドシートを作成します（名前は自由です。例: 「${brief.brand.name} 受付管理」）。
2. URL の \`/d/\` と \`/edit\` の間の文字列が **スプレッドシートID** です。控えておきます。

## 2. Apps Script にプログラムを入れる（作業者向け）

\`\`\`bash
cd gas
npm install
npm test          # 全テストが通ることを確認
npm run build
cp .clasp.json.example .clasp.json   # scriptId を記入
npx clasp push
\`\`\`

## 3. スクリプト プロパティを設定する

Apps Script エディタ →「プロジェクトの設定」→「スクリプト プロパティ」に次を登録します。
**これらの値はスプレッドシートやチャット、Git には絶対に書かないでください。**

| プロパティ | 内容 |
|---|---|
| \`SPREADSHEET_ID\` | 手順1のスプレッドシートID |
| \`LINE_CHANNEL_ACCESS_TOKEN\` | LINE Developers →「Messaging API設定」のチャネルアクセストークン（長期） |
| \`WEBHOOK_KEY\` | 32文字以上のランダムな英数字（パスワード生成ツールで作成） |
| \`RICH_MENU_IMAGE_FILE_ID\` | 手順7で Google ドライブに置くリッチメニュー画像のファイルID |
| \`API_ENABLED\` | 通常は設定しません（将来の Web 予約画面を接続するときだけ \`true\`） |

## 4. シートを自動作成する

エディタ上部の関数選択で **setupSpreadsheet** を選び「実行」します（初回は権限の承認が必要です）。
次のシートが作られます: ${schema.sheets.map((s) => `\`${s.name}\``).join("、")}。
何度実行しても、既存のデータは消えません（足りないシート・列・設定だけを追加します）。

## 5. 店舗情報を入力する

- \`CONFIG\` シートの \`value\` 列を確認・入力します。${missingRequired.length > 0 ? `\n  - **必ず入力が必要:** ${missingRequired.map((k) => `\`${k}\``).join("、")}` : ""}
${hasReservation ? "  - 営業時間は `hours.mon` 〜 `hours.sun` に `10:00-19:00` の形式で、定休日は `closed` と入力します。\n  - `reservation.capacity` は同じ時間に受けられる人数（席数・スタッフ数）です。\n" : ""}${hasDataSheets ? "- 必要に応じて、各ワークフローで使用する情報を該当するシートに入力します。`active` を設定できる項目は、TRUE にした行のみが使用されます。\n" : ""}
## 6. Web アプリとして公開し、LINE とつなぐ

1. エディタ右上「デプロイ」→「新しいデプロイ」→ 種類「ウェブアプリ」。
   - 次のユーザーとして実行: 自分／アクセスできるユーザー: 全員
2. 表示された URL の末尾に \`?key=<WEBHOOK_KEY の値>\` を付けたものを、
   LINE Developers の「Webhook URL」に設定し、「Webhook の利用」をオンにします。
3. LINE Official Account Manager の「応答設定」で、Webhook をオンにします。
   （自動応答メッセージは、必要に応じてオフにしてください）

## 7. リッチメニューを登録する

1. \`rich-menu/design-spec.json\` の仕様で画像を作成します（ボタン: ${buttons}）。
2. 画像を Google ドライブにアップロードし、ファイルIDを \`RICH_MENU_IMAGE_FILE_ID\` に設定します。
3. エディタで **setupRichMenu** を実行します。全員のトーク画面にメニューが表示されます。

## 8. 動作確認（チェックリスト）

${input.menuConfig.areas.map((a) => `- [ ] 「${a.action.label}」をタップして、正しい返信・画面が出る`).join("\n")}
${plan.selected.some((w) => w.id.startsWith("inquiry-")) ? "- [ ] お問い合わせを送ると、`INQUIRIES` シートに行が追加され、通知メールが届く\n" : ""}${hasReservation ? "- [ ] 予約日時を選ぶと、`RESERVATIONS` シートに `REQUESTED` の行が追加され、通知メールが届く\n- [ ] 定休日・営業時間外を選ぶと「ご予約いただけません」と返信される\n" : ""}
## 9. 毎日の運用

${hasReservation ? "- 予約リクエストが届いたら内容を確認し、`RESERVATIONS` の `status` を `CONFIRMED`（確定）または `CANCELLED` に変更してください。お客様への確定連絡は LINE チャットで行います。\n" : ""}- お問い合わせは \`INQUIRIES\` の \`status\` を \`IN_PROGRESS\` → \`DONE\` と更新すると管理しやすくなります。
- シートの **見出し行（1行目）は変更・削除しないでください**。システムが列を見つけられなくなります。

## セキュリティについて

- スプレッドシートにはお客様の個人情報（LINE ID・お名前・連絡先）が入ります。共有は必要な方だけにしてください。
- トークンや \`WEBHOOK_KEY\` が漏れた場合は、LINE Developers でトークンを再発行し、\`WEBHOOK_KEY\` も新しい値に変更してください。
${footer(trace)}`;
}

export function deliveryMd(input: DeliveryInputs): string {
  const { brief, profile, plan, trace } = input;
  return `# 納品書（成果物一覧） — ${brief.project.clientName}

## 今回の構成

- 業種プロファイル: ${profile.industryAsset}（${profile.displayName}）
- リッチメニュー: ${plan.richMenu}／デザインプリセット: ${plan.designPreset}
- ワークフロー:
${plan.selected.map((w) => `  - **${w.name}** (\`${w.id}@${w.version}\`): ${w.reasons.join(", ") || "—"}`).join("\n")}
${plan.deferred.length > 0 ? `- 今回は見送ったもの:\n${plan.deferred.map((d) => `  - \`${d.id}\`: ${d.reason}`).join("\n")}\n` : ""}
## 成果物

| ファイル | 内容 |
|---|---|
${input.artifacts.map((a) => `| \`${a}\` | ${describeArtifact(a)} |`).join("\n")}

## 今回の範囲に含まれないもの（Phase 1）

- お客様向けの Web 予約画面・LIFF アプリ（Phase 2 で対応予定）
- 予約の自動確定、Google カレンダー連携、スタッフ指名、キャンセル受付
- LINE でのお客様への自動プッシュ通知（リマインド等）

## 前提・注意事項

${[...profile.assumptions, ...profile.risks].map((a) => `- ${a}`).join("\n")}

## 品質確認

自動品質チェックの結果は \`qa/QA_REPORT.md\` を参照してください。

## 今後の拡張候補

${[
  ...plan.extensionPoints.map((p) => `- \`${p.workflow}\` / ${p.id}: ${p.description}`),
  ...(profile.extensionPoints?.planned ?? []).map((p) => `- \`${profile.industryAsset}\` / ${p.id}: ${p.description}`),
].join("\n")}
${footer(trace)}`;
}

function describeArtifact(file: string): string {
  const map: Record<string, string> = {
    "project.json": "プロジェクト情報とトレーサビリティ",
    "brief/brief.json": "ご要望（入力データ）",
    "brief/business-requirements.md": "ご要望まとめ",
    "analysis/industry-profile.json": "業種分析",
    "workflow/selected-workflows.json": "採用したワークフローと理由",
    "workflow/workflow.json": "ワークフロー・アクション定義（このプロジェクト用の固定コピー）",
    "rich-menu/design-spec.json": "リッチメニュー画像のデザイン仕様",
    "rich-menu/menu-config.json": "LINE に登録するリッチメニュー設定",
    "spreadsheet/schema.json": "スプレッドシートの構成（シート・列・設定項目）",
    "spreadsheet/config-seed.json": "CONFIG シートの初期値",
    "gas/": "Google Apps Script プログラム一式（テスト付き）",
    "delivery/SETUP.md": "セットアップ手順",
    "delivery/DELIVERY.md": "この納品書",
    "qa/qa-report.json": "品質チェック結果（機械可読）",
    "qa/QA_REPORT.md": "品質チェック結果",
  };
  return map[file] ?? "";
}
