import type { IndustryProfile } from "../agents/industrySpecialist";
import type { WorkflowPlan } from "../agents/workflowPlanner";
import type { ImageRecord } from "../richMenu/renderer";
import type { ClientBrief } from "../schemas/brief";
import type { TraceContext } from "./meta";
import { FACTORY_VERSION } from "./meta";
import type { LineRichMenuConfig, LineRoute } from "./richMenuConfig";
import type { ProjectSchema } from "./spreadsheetSchema";

/**
 * Client-facing documents. They are written in plain Japanese for a
 * non-technical owner (same tone as apps/hair-salon-portfolio/docs/owner-guide.md).
 * Steps only a technical installer does are marked 「作業者向け」.
 *
 *   SETUP.md              the whole setup, in order, with links to:
 *   SPREADSHEET_SETUP.md  sheets, columns and settings
 *   GAS_SETUP.md          the Apps Script program (installer)
 *   LINE_SETUP.md         LINE channel, signature-check proxy, rich menu
 *   E2E_TEST.md           smartphone test checklist
 *   ROLLBACK.md           how to go back when something goes wrong
 *   DELIVERY.md           what is and is not included, and who does what
 */

export interface DeliveryInputs {
  brief: ClientBrief;
  profile: IndustryProfile;
  plan: WorkflowPlan;
  schema: ProjectSchema;
  configSeed: Record<string, string>;
  menuConfig: LineRichMenuConfig;
  routes: LineRoute[];
  image: ImageRecord;
  trace: TraceContext;
  artifacts: string[];
}

export const DELIVERY_DOCS = [
  "delivery/SETUP.md",
  "delivery/SPREADSHEET_SETUP.md",
  "delivery/GAS_SETUP.md",
  "delivery/LINE_SETUP.md",
  "delivery/E2E_TEST.md",
  "delivery/ROLLBACK.md",
  "delivery/DELIVERY.md",
] as const;

const footer = (trace: TraceContext) =>
  `\n---\n\n<sub>Generated by AI-Agent-Coconala-Factory ${FACTORY_VERSION} for ${trace.project} (${trace.industry}; ${trace.workflows.join(", ")}).</sub>\n`;

const hasWorkflow = (plan: WorkflowPlan, prefix: string) => plan.selected.some((w) => w.id.startsWith(prefix));

/** What the customer sees after tapping a button, derived from the button's LINE action and route. */
function expectedResult(area: LineRichMenuConfig["areas"][number], routes: LineRoute[]): string {
  const action = area.action;
  if (action.type === "uri") return "ブラウザで Web ページが開く";
  if (action.type === "datetimepicker") return "日時を選ぶ画面が出て、選ぶと「予約リクエストを受け付けました」と返信が届く";
  const params = Object.fromEntries((action.data ?? "").split("&").map((pair) => pair.split("=")));
  const route = routes.find((r) => r.workflowId === params.wf && r.entry === (params.e ?? "default"));
  if (route?.mode === "awaitText") return "案内メッセージが届き、続けて内容を送ると「受け付けました」と受付番号が届く";
  return "店舗の情報がメッセージで届く";
}

export function businessRequirementsMd(brief: ClientBrief, trace: TraceContext): string {
  return `# ご要望まとめ — ${brief.project.clientName}

- 業種: ${brief.industry}${brief.businessType ? `（${brief.businessType}）` : ""}
- ブランド名: ${brief.brand.name}${brief.brand.tone ? `／トーン: ${brief.brand.tone}` : ""}

## お客様にできるようにしたいこと

${brief.requirements.length > 0 ? brief.requirements.map((r) => `- ${r}`).join("\n") : "- （記載なし。業種の標準構成を使用）"}

## 既にお持ちのもの

${brief.existingResources.length > 0 ? brief.existingResources.map((r) => `- ${r}`).join("\n") : "- （記載なし）"}
${footer(trace)}`;
}

export function setupMd(input: DeliveryInputs): string {
  const { brief, schema, plan, trace } = input;
  const hasReservation = hasWorkflow(plan, "reservation-");
  // Owner-curated data sheets have an `active` column. Wording stays domain-neutral: no sheet names, not every business has a menu.
  const hasDataSheets = schema.sheets.some((s) => s.columns.some((c) => c.name === "active"));
  const missingRequired = schema.configKeys.filter((k) => k.required && !(k.key in input.configSeed) && k.default === undefined).map((k) => k.key);

  return `# セットアップ手順 — ${brief.project.clientName}

この手順書は、LINE リッチメニューと Google スプレッドシートを使った自動受付の初期設定を、順番どおりにまとめたものです。
各手順の詳しい説明は、リンク先の資料にあります。「作業者向け」とある手順は、納品担当の作業者が行います。
作業時間の目安: 90〜120分。

## 仕組み（全体像）

\`\`\`text
お客様のスマートフォン（LINE アプリ）
   │ リッチメニューのボタンをタップ
   ▼
LINE ──► 署名確認プロキシ（本物の LINE からの通信かを確認）──► Google Apps Script ──► スプレッドシート
                                                                   │
                                                                   └─► LINE で自動返信・オーナー様へ通知メール
\`\`\`

## 0. 事前に用意するもの

- LINE 公式アカウント（Messaging API を有効化済み）
- Google アカウント（スプレッドシートと Apps Script を作成するアカウント）
- Cloudflare アカウント（無料プランで可。署名確認プロキシを置く場所です）
- スマートフォン（LINE アプリ）。**リッチメニューはパソコン版 LINE には表示されません。**
- リッチメニュー画像は納品物に含まれています（\`rich-menu/rich-menu.png\`、${input.image.width}×${input.image.height}px、${Math.ceil(input.image.bytes / 1024)}KB）。

## 1. スプレッドシートを作る

1. Google ドライブで新しいスプレッドシートを作成します（名前は自由です。例: 「${brief.brand.name} 受付管理」）。
2. URL の \`/d/\` と \`/edit\` の間の文字列が **スプレッドシートID** です。控えておきます。

シートと列の一覧は [SPREADSHEET_SETUP.md](SPREADSHEET_SETUP.md) を参照してください。

## 2. Apps Script にプログラムを入れる（作業者向け）

\`\`\`bash
cd gas
npm install
npm test          # 全テストが通ることを確認
npm run build
cp .clasp.json.example .clasp.json   # scriptId を記入
npx clasp push
\`\`\`

詳しくは [GAS_SETUP.md](GAS_SETUP.md) を参照してください。

## 3. スクリプト プロパティを設定する

Apps Script エディタ →「プロジェクトの設定」→「スクリプト プロパティ」に次を登録します。
**これらの値はスプレッドシートやチャット、Git には絶対に書かないでください。**

| プロパティ | 内容 |
|---|---|
| \`SPREADSHEET_ID\` | 手順1のスプレッドシートID |
| \`LINE_CHANNEL_ACCESS_TOKEN\` | LINE Developers →「Messaging API設定」のチャネルアクセストークン（長期） |
| \`WEBHOOK_KEY\` | 32文字以上のランダムな英数字（パスワード生成ツールで作成）。署名確認プロキシにも同じ値を設定します |
| \`API_ENABLED\` | 通常は設定しません（将来の Web 予約画面を接続するときだけ \`true\`） |

## 4. シートを自動作成する

エディタ上部の関数選択で **setupSpreadsheet** を選び「実行」します（初回は権限の承認が必要です）。
次のシートが作られます: ${schema.sheets.map((s) => `\`${s.name}\``).join("、")}。
何度実行しても、既存のデータは消えません（足りないシート・列・設定だけを追加します）。

## 5. 店舗情報を入力する

- \`CONFIG\` シートの \`value\` 列を確認・入力します。${missingRequired.length > 0 ? `\n  - **必ず入力が必要:** ${missingRequired.map((k) => `\`${k}\``).join("、")}` : ""}
${hasReservation ? "  - 営業時間は `hours.mon` 〜 `hours.sun` に `10:00-19:00` の形式で、定休日は `closed` と入力します。\n  - `reservation.capacity` は同じ時間に受けられる人数（席数・スタッフ数）です。\n" : ""}${hasDataSheets ? "- 必要に応じて、各ワークフローで使用する情報を該当するシートに入力します。`active` を設定できる項目は、TRUE にした行のみが使用されます。\n" : ""}
## 6. Web アプリとして公開する（作業者向け）

1. エディタ右上「デプロイ」→「新しいデプロイ」→ 種類「ウェブアプリ」。
   - 次のユーザーとして実行: 自分／アクセスできるユーザー: 全員
2. 表示された URL（\`…/exec\`）を控えます。**この URL は LINE には直接設定しません。** 次の手順の署名確認プロキシに設定します。

## 7. 署名確認プロキシを置き、LINE とつなぐ（作業者向け）

LINE から届く通信が本物かどうかを確かめる小さなプログラム（署名確認プロキシ）を Cloudflare に置き、
その URL を LINE の Webhook URL に設定します。手順は [LINE_SETUP.md](LINE_SETUP.md) の「2」「3」です。

## 8. リッチメニューを登録する（作業者向け）

納品物の画像と設定を、ファクトリーのコマンドで LINE に登録します。まずテスト用アカウントで確認し、問題がなければ本番に登録します。
手順は [LINE_SETUP.md](LINE_SETUP.md) の「4」です。

## 9. 動作確認

スマートフォンの LINE アプリで [E2E_TEST.md](E2E_TEST.md) のチェックリストを上から順に確認します。

## 10. 毎日の運用

${hasReservation ? "- 予約リクエストが届いたら内容を確認し、`RESERVATIONS` の `status` を `CONFIRMED`（確定）または `CANCELLED` に変更してください。お客様への確定連絡は LINE チャットで行います。\n" : ""}- お問い合わせは \`INQUIRIES\` の \`status\` を \`IN_PROGRESS\` → \`DONE\` と更新すると管理しやすくなります。
- シートの **見出し行（1行目）は変更・削除しないでください**。システムが列を見つけられなくなります。

## うまく動かないとき・元に戻したいとき

[ROLLBACK.md](ROLLBACK.md) を参照してください。リッチメニュー、LINE との接続、プログラム、設定のそれぞれを元に戻す方法があります。

## セキュリティについて

- スプレッドシートにはお客様の個人情報（LINE ID・お名前・連絡先）が入ります。共有は必要な方だけにしてください。
- チャネルアクセストークン、チャネルシークレット、\`WEBHOOK_KEY\` はパスワードと同じです。漏れた場合は LINE Developers でトークンを再発行し、チャネルシークレットと \`WEBHOOK_KEY\` も新しい値に変更してください（[ROLLBACK.md](ROLLBACK.md)「4」）。
${footer(trace)}`;
}

export function spreadsheetSetupMd(input: DeliveryInputs): string {
  const { brief, schema, configSeed, trace } = input;
  const sheets = schema.sheets
    .map((sheet) => {
      const rows = sheet.columns.map((c) => `| \`${c.name}\` | ${c.required ? "必須" : ""} | ${c.description}${c.pii ? "（個人情報）" : ""} |`);
      return `### \`${sheet.name}\`\n\n| 列 | | 内容 |\n|---|---|---|\n${rows.join("\n")}`;
    })
    .join("\n\n");
  const config = schema.configKeys.map((k) => {
    const value = configSeed[k.key] ?? k.default;
    return `| \`${k.key}\` | ${k.required ? "必須" : ""} | ${k.description} | ${value !== undefined ? `\`${value}\`` : "（未入力）"} |`;
  });
  return `# スプレッドシートの構成 — ${brief.project.clientName}

シートは Apps Script の **setupSpreadsheet** で自動作成されます（[SETUP.md](SETUP.md)「4」）。手で作る必要はありません。
**1行目（見出し）の名前は変更しないでください。** 列の順番の入れ替えや、右側への列の追加は問題ありません。

## シートと列

${sheets}

## \`CONFIG\` シートの設定項目

初期値はご要望の内容から入力済みです。変更は \`value\` 列を書き換えるだけで、すぐに反映されます。

| key | | 内容 | 初期値 |
|---|---|---|---|
${config.join("\n")}

## 個人情報の扱い

「（個人情報）」と書かれた列には、お客様の LINE ID・お名前・連絡先・お問い合わせ内容が入ります。
スプレッドシートの共有は必要な方だけにし、不要になったデータは定期的に削除してください。
${footer(trace)}`;
}

export function gasSetupMd(input: DeliveryInputs): string {
  const { brief, trace } = input;
  return `# Apps Script（GAS）の設定 — ${brief.project.clientName}

作業者向けの資料です。オーナー様が操作するのは「5. 更新したとき」の確認だけです。

## 1. プログラムを入れる

\`\`\`bash
cd gas
npm install
npm run typecheck
npm test            # LINE の受付テストを含む全テストが通ることを確認
npm run build       # build/Code.js を作成
cp .clasp.json.example .clasp.json   # scriptId を記入（.clasp.json は Git に入れない）
npx clasp push
\`\`\`

## 2. スクリプト プロパティ

[SETUP.md](SETUP.md)「3」の表のとおりに登録します。値はここ以外（ファイル、チャット、スプレッドシート）には書きません。

## 3. ウェブアプリとして公開

「デプロイ」→「新しいデプロイ」→「ウェブアプリ」。実行ユーザー: 自分、アクセス: 全員。
表示される \`…/exec\` の URL は、署名確認プロキシの \`GAS_WEBAPP_URL\` に設定します（[LINE_SETUP.md](LINE_SETUP.md)「2」）。

- LINE からの通信は、署名確認プロキシを通ったものだけが受け付けられます（URL に \`WEBHOOK_KEY\` が付いているもののみ）。
- \`WEBHOOK_KEY\` が未設定、または 16 文字未満のときは、すべての LINE の通信を拒否します。

## 4. 初回の実行

1. **setupSpreadsheet** を実行してシートを作ります。
2. 実行ログ（「実行数」）にエラーがないことを確認します。

## 5. 更新したとき

プログラムを更新したら「デプロイを管理」→ 既存のデプロイを「編集」→ バージョン「新しいバージョン」で更新します。
**新しいデプロイを作ると URL が変わる**ため、署名確認プロキシの設定も変更が必要になります。

## 補足: setupRichMenu

GAS の **setupRichMenu** 関数でもリッチメニューを登録できますが、通常はファクトリーの \`line-deploy\` を使います
（登録結果が記録され、元に戻すことができるためです。[LINE_SETUP.md](LINE_SETUP.md)「4」）。
${footer(trace)}`;
}

export function lineSetupMd(input: DeliveryInputs): string {
  const { brief, menuConfig, trace } = input;
  const slugPath = `projects/${trace.project}`;
  return `# LINE の設定 — ${brief.project.clientName}

## 仕組み

\`\`\`text
LINE ──► 署名確認プロキシ（Cloudflare Worker）──► Google Apps Script ──► スプレッドシート
          │ 本物の LINE からの通信か「署名」で確認
          └ 確認できない通信はここで止め、Apps Script には送りません
\`\`\`

Google Apps Script は LINE の「署名」を確認できないため、確認を署名確認プロキシが行います。
Apps Script はプロキシからの通信だけを受け付けます（\`WEBHOOK_KEY\`）。

## 1. LINE Developers で確認する値

| 値 | 場所 | 設定先 |
|---|---|---|
| チャネルシークレット | 「チャネル基本設定」 | 署名確認プロキシ（\`LINE_CHANNEL_SECRET\`） |
| チャネルアクセストークン（長期） | 「Messaging API設定」 | Apps Script（\`LINE_CHANNEL_ACCESS_TOKEN\`）、リッチメニュー登録時の作業者の環境変数 |

どちらもパスワードと同じ扱いです。ファイル・チャット・スプレッドシートに書かないでください。

## 2. 署名確認プロキシを置く（作業者向け）

\`\`\`bash
cd line/webhook
npm install
npm test                                  # 署名確認のテスト
cp wrangler.toml.example wrangler.toml
npx wrangler login
npx wrangler secret put LINE_CHANNEL_SECRET   # 1 のチャネルシークレット
npx wrangler secret put GAS_WEBAPP_URL        # GAS の …/exec の URL
npx wrangler secret put GAS_WEBHOOK_KEY       # Apps Script の WEBHOOK_KEY と同じ値
npx wrangler deploy                           # https://….workers.dev の URL が表示されます
\`\`\`

## 3. Webhook を設定する

1. LINE Developers →「Messaging API設定」→「Webhook URL」に、手順2で表示された **workers.dev の URL** を設定します（Apps Script の URL ではありません）。
2. 「検証」を押して「成功」と表示されることを確認します。
3. 「Webhookの利用」をオンにします。
4. LINE Official Account Manager の「応答設定」で Webhook をオンにします（自動応答メッセージは必要に応じてオフ）。
5. 任意: 「Webhookの再送」をオンにすると、一時的な障害のときに LINE が通信を再送します。同じ通信が2回届いても、受付は1回だけ記録されます。

## 4. リッチメニューを登録する（作業者向け）

リッチメニュー「${menuConfig.name}」（${menuConfig.size.width}×${menuConfig.size.height}px、ボタン${menuConfig.areas.length}個）を、ファクトリーから登録します。
トークンは環境変数でだけ渡します（ファイルに保存しません）。

\`\`\`bash
# 1) 確認だけ（LINE には何も送りません）
npm run factory -- line-deploy --project ${slugPath} --env test
# 2) テスト用 LINE 公式アカウントに登録
LINE_CHANNEL_ACCESS_TOKEN=（テスト用のトークン） npm run factory -- line-deploy --project ${slugPath} --env test --live
# 3) E2E_TEST.md で確認したあと、本番アカウントに登録
LINE_CHANNEL_ACCESS_TOKEN=（本番のトークン） npm run factory -- line-deploy --project ${slugPath} --env production --live
\`\`\`

- 登録は「作成 → 画像の登録 → 確認 → 全員に表示」の順で行い、**古いメニューは削除しません。** 前のメニューは記録され、いつでも戻せます（[ROLLBACK.md](ROLLBACK.md)）。
- 登録結果（LINE が発行するメニューID）は \`line/deployment-history.json\` に記録されます。
- リッチメニューは **スマートフォンの LINE アプリでだけ** 表示されます（パソコン版 LINE には表示されません）。表示の反映には少し時間がかかることがあります。
${footer(trace)}`;
}

export function e2eTestMd(input: DeliveryInputs): string {
  const { brief, plan, menuConfig, routes, trace } = input;
  const hasReservation = hasWorkflow(plan, "reservation-");
  const hasInquiry = hasWorkflow(plan, "inquiry-");
  return `# 動作確認（スマートフォン） — ${brief.project.clientName}

## 対応環境

- **iPhone / Android の LINE アプリ（最新版）** で確認します。
- **パソコン版 LINE（Windows / Mac）ではリッチメニューが表示されないため、確認には使えません。**
- 最初は **テスト用の LINE 公式アカウント** で確認し、問題がなければ本番アカウントで同じ確認をします。
- 確認用の LINE アカウントは、オーナー様・作業者のものを使ってください（実際のお客様の情報は使いません）。

## 1. リッチメニューの表示

- [ ] トーク画面の下にリッチメニューが表示される（チャットバーの文字: 「${menuConfig.chatBarText}」）
- [ ] 画像の文字が読める・ボタンの位置と画像の絵が合っている

## 2. ボタンごとの確認

| | ボタン | 期待する結果 |
|---|---|---|
${menuConfig.areas.map((a) => `| [ ] | ${a.action.label} | ${expectedResult(a, routes)} |`).join("\n")}

## 3. スプレッドシートと通知

${hasInquiry ? "- [ ] お問い合わせを送ると、`INQUIRIES` シートに1行追加され、オーナー様に通知メールが届く\n" : ""}${hasReservation ? "- [ ] 予約日時を選ぶと、`RESERVATIONS` シートに `REQUESTED`（リクエスト）の行が1行追加され、通知メールが届く\n- [ ] 返信メッセージが「確定」ではなく「リクエストを受け付けました」になっている（予約はオーナー様の確認後に確定します）\n" : ""}- [ ] 同じボタンを続けて押しても、エラーにならない

## 4. まちがった入力

${hasReservation ? "- [ ] 定休日・営業時間外・過去の日時を選ぶと「ご希望の日時はご予約いただけません。別の日時をお選びください。」と返信され、行は増えない\n" : ""}${hasInquiry ? "- [ ] お問い合わせで、案内のあと10分以上たってから送ったメッセージは受付されない（通常のチャットとして届く）\n" : ""}- [ ] どの場合も、英語のエラーや内部の情報（URL・ID）が表示されない

## 5. 自動テストで確認済みの項目

次の項目は納品前に自動テストで確認しています（\`qa/LINE_QA_REPORT.md\`）。実機での再確認は不要です。

- 同じ通信が2回届いても（LINE の再送）、受付・返信は1回だけ
- 署名のない通信・改ざんされた通信は Apps Script に届かない
- 登録されていないボタン・操作には安全なメッセージだけを返す

## 確認記録

| 日付 | アカウント（テスト/本番） | 端末・OS | 確認者 | 結果 |
|---|---|---|---|---|
| | | | | |
${footer(trace)}`;
}

export function rollbackMd(input: DeliveryInputs): string {
  const { brief, trace } = input;
  const slugPath = `projects/${trace.project}`;
  return `# 元に戻す方法 — ${brief.project.clientName}

困ったときは、まず「どこを戻すか」を決めます。どの手順も、お客様のデータ（スプレッドシート）は消しません。

## 1. リッチメニューを前のものに戻す

作業者向け（ファクトリーから）:

\`\`\`bash
npm run factory -- line-rollback --project ${slugPath} --env production          # 確認だけ
LINE_CHANNEL_ACCESS_TOKEN=… npm run factory -- line-rollback --project ${slugPath} --env production --live
\`\`\`

- 直前に登録していたメニューを「全員に表示」に戻します。メニューは削除しません。
- 登録前にメニューがなかった場合は戻す先がないため、LINE Official Account Manager でメニューを表示する設定にするか、作業者が \`line/deployment-history.json\` を確認して対応します。
- 不要になったメニューの削除は、表示中でないことを確認してから \`line-delete --rich-menu-id <ID> --live\` で行います（表示中のメニューは削除できないようになっています）。

## 2. LINE との接続（Webhook）を止める・戻す

- **すぐに止めたいとき:** LINE Developers →「Messaging API設定」→「Webhookの利用」をオフにします。自動受付は止まり、通常のチャットと自動応答メッセージだけになります。
- **Webhook URL を間違えたとき:** 署名確認プロキシの \`…workers.dev\` の URL に設定し直し、「検証」で成功を確認します。
- 署名確認プロキシを前の版に戻す（作業者向け）: \`cd line/webhook && npx wrangler rollback\`。

## 3. プログラム（Apps Script）を前の版に戻す

Apps Script エディタ →「デプロイを管理」→ 使用中のデプロイを「編集」→「バージョン」で前の版を選んで「デプロイ」。
URL は変わらないため、署名確認プロキシや LINE の設定は変更不要です。

## 4. 設定を元に戻す

- **\`CONFIG\` シート:** スプレッドシートの「ファイル」→「変更履歴」から、以前の状態に戻せます。
- **スクリプト プロパティ・プロキシの値:** 画面に表示されない値のため、パスワード管理ツールに控えておき、必要なら同じ画面で入れ直します。
- **漏えいしたとき:** LINE Developers でチャネルアクセストークンを再発行し、チャネルシークレットも再発行します。
  新しい値を Apps Script（\`LINE_CHANNEL_ACCESS_TOKEN\`）と署名確認プロキシ（\`npx wrangler secret put LINE_CHANNEL_SECRET\`）に設定し、
  \`WEBHOOK_KEY\` も新しい値にして Apps Script とプロキシ（\`GAS_WEBHOOK_KEY\`）の両方を更新します。

## 記録

登録・切り戻しの履歴は \`line/deployment-history.json\` にあります（トークンなどの秘密の値は記録されません）。
${footer(trace)}`;
}

export function deliveryMd(input: DeliveryInputs): string {
  const { brief, profile, plan, trace, image } = input;
  const assetRows = Object.entries(trace.assets).map(([id, version]) => `| \`${id}\` | ${version} |`);
  return `# 納品書（成果物一覧） — ${brief.project.clientName}

## 今回の構成

- 業種プロファイル: ${profile.industryAsset}（${profile.displayName}）
- リッチメニュー: ${plan.richMenu}／デザインプリセット: ${plan.designPreset}
- リッチメニュー画像: \`rich-menu/rich-menu.png\`（${image.width}×${image.height}px、PNG、sha256 \`${image.sha256.slice(0, 16)}…\`）
- ワークフロー:
${plan.selected.map((w) => `  - **${w.name}** (\`${w.id}@${w.version}\`): ${w.reasons.join(", ") || "—"}`).join("\n")}
${plan.deferred.length > 0 ? `- 今回は見送ったもの:\n${plan.deferred.map((d) => `  - \`${d.id}\`: ${d.reason}`).join("\n")}\n` : ""}
## 含まれるもの

- LINE リッチメニュー（画像・ボタン設定）と、その登録・切り戻しの手順
- ボタンからの自動受付・自動返信（Google Apps Script）
- 受付内容を記録する Google スプレッドシートの構成と自動作成
- 本物の LINE からの通信だけを受け付ける署名確認プロキシ
- 品質チェック結果（\`qa/QA_REPORT.md\`、\`qa/LINE_QA_REPORT.md\`）と、この資料一式

## 含まれないもの

- お客様向けの Web 予約画面・LIFF アプリ
- 予約の自動確定、Google カレンダー連携、スタッフ指名、キャンセル受付、来店履歴
- LINE でのお客様への自動プッシュ通知（リマインド等）
- LINE 公式アカウント・Google・Cloudflare の利用料金、アカウントの開設

## お客様にご用意・ご対応いただくこと

- LINE 公式アカウント（Messaging API を有効化）と、テスト用の LINE 公式アカウント（推奨）
- Google アカウント、Cloudflare アカウント（無料プランで可）
- 店舗情報・営業時間の確認と入力（\`CONFIG\` シート）
- 受付後のご対応（予約の確定連絡、お問い合わせへの返信）と、スプレッドシートの共有範囲の管理
- スマートフォンでの最終確認（[E2E_TEST.md](E2E_TEST.md)）

## 納品側で行う設定

- Apps Script へのプログラムの設置と公開（[GAS_SETUP.md](GAS_SETUP.md)）
- 署名確認プロキシの設置と Webhook の設定、リッチメニューの登録（[LINE_SETUP.md](LINE_SETUP.md)）
- スプレッドシートの自動作成と初期値の入力（[SPREADSHEET_SETUP.md](SPREADSHEET_SETUP.md)）

## LINE アカウントの条件

- Messaging API が有効な LINE 公式アカウント（チャネルアクセストークン・チャネルシークレットが発行できること）
- リッチメニューはスマートフォンの LINE アプリで表示されます（パソコン版 LINE には表示されません）

## テスト

- 自動テスト: プログラム・署名確認・ボタンごとの受付を納品前に自動で確認しています（\`qa/\`）。
- 実機テスト: テスト用アカウントとスマートフォンで [E2E_TEST.md](E2E_TEST.md) を確認し、記録欄に記入します。
  実機での確認は、LINE アカウントの準備ができてから行うため、納品物の自動チェックには含まれません。

## 成果物

| ファイル | 内容 |
|---|---|
${input.artifacts.map((a) => `| \`${a}\` | ${describeArtifact(a)} |`).join("\n")}

## 前提・注意事項

${[...profile.assumptions, ...profile.risks].map((a) => `- ${a}`).join("\n")}

## 品質確認

自動品質チェックの結果は \`qa/QA_REPORT.md\`（全体）と \`qa/LINE_QA_REPORT.md\`（LINE 連携）を参照してください。

## 使用した部品と版（トレーサビリティ）

ファクトリー ${FACTORY_VERSION}／画像レンダラー ${image.renderer.id}@${image.renderer.version}

| 部品 | 版 |
|---|---|
${assetRows.join("\n")}

## 今後の拡張候補

${[
  ...plan.extensionPoints.map((p) => `- \`${p.workflow}\` / ${p.id}: ${p.description}`),
  ...(profile.extensionPoints?.planned ?? []).map((p) => `- \`${profile.industryAsset}\` / ${p.id}: ${p.description}`),
  "- （任意）お客様向け Web 予約画面（Next.js / LIFF）、Canva 連携による画像デザイン、AI による受付内容の整理",
].join("\n")}
${footer(trace)}`;
}

function describeArtifact(file: string): string {
  const map: Record<string, string> = {
    "project.json": "プロジェクト情報とトレーサビリティ",
    "brief/brief.json": "ご要望（入力データ）",
    "brief/business-requirements.md": "ご要望まとめ",
    "analysis/industry-profile.json": "業種分析",
    "workflow/selected-workflows.json": "採用したワークフローと理由",
    "workflow/workflow.json": "ワークフロー・アクション定義（このプロジェクト用の固定コピー）",
    "rich-menu/design-spec.json": "リッチメニュー画像のデザイン仕様",
    "rich-menu/menu-config.json": "LINE に登録するリッチメニュー設定",
    "rich-menu/rich-menu.png": "LINE に登録するリッチメニュー画像",
    "rich-menu/preview.svg": "リッチメニュー画像のプレビュー（画像の元データ）",
    "rich-menu/image.json": "画像の情報（サイズ・ハッシュ・作成ツールの版）",
    "spreadsheet/schema.json": "スプレッドシートの構成（シート・列・設定項目）",
    "spreadsheet/config-seed.json": "CONFIG シートの初期値",
    "gas/": "Google Apps Script プログラム一式（テスト付き）",
    "line/deployment.json": "LINE への登録内容と、ボタンからプログラムまでの対応表",
    "line/README.md": "LINE 登録の作業者向けメモ",
    "line/webhook/": "署名確認プロキシ（Cloudflare Worker、テスト付き）",
    "delivery/SETUP.md": "セットアップ手順（全体）",
    "delivery/SPREADSHEET_SETUP.md": "スプレッドシートの構成と設定項目",
    "delivery/GAS_SETUP.md": "Apps Script の設定（作業者向け）",
    "delivery/LINE_SETUP.md": "LINE・署名確認プロキシ・リッチメニューの設定",
    "delivery/E2E_TEST.md": "スマートフォンでの動作確認チェックリスト",
    "delivery/ROLLBACK.md": "元に戻す方法",
    "delivery/DELIVERY.md": "この納品書",
    "qa/qa-report.json": "品質チェック結果（機械可読）",
    "qa/QA_REPORT.md": "品質チェック結果",
    "qa/line-qa-report.json": "LINE 連携の品質チェック結果（機械可読）",
    "qa/LINE_QA_REPORT.md": "LINE 連携の品質チェック結果",
  };
  return map[file] ?? "";
}
