import { readJson } from "../lib/fsx";
import path from "node:path";
import { FACTORY_ROOT } from "../lib/fsx";

/**
 * Traceability block attached to every generated JSON artifact (`_meta`)
 * and, as a header comment, to every generated source file. It answers
 * "which project, industry, workflows and asset versions produced this?"
 * (Rule 9). No timestamps, so regenerating unchanged inputs gives
 * byte-identical output.
 */
export interface ArtifactMeta {
  artifact: string;
  generatedBy: string;
  factoryVersion: string;
  project: string;
  industry: string;
  workflows: string[];
  assets: Record<string, string>;
}

export const FACTORY_VERSION: string = readJson<{ version: string }>(path.join(FACTORY_ROOT, "package.json")).version;

export interface TraceContext {
  project: string;
  industry: string;
  /** `id@version` of each selected workflow. */
  workflows: string[];
  /** asset id -> version, for every Core Asset the project depends on. */
  assets: Record<string, string>;
}

export function meta(artifact: string, generatedBy: string, trace: TraceContext): ArtifactMeta {
  return {
    artifact,
    generatedBy,
    factoryVersion: FACTORY_VERSION,
    project: trace.project,
    industry: trace.industry,
    workflows: trace.workflows,
    assets: trace.assets,
  };
}

export function sourceHeader(trace: TraceContext, generatedBy: string): string {
  return [
    "/*",
    ` * GENERATED by AI-Agent-Coconala-Factory ${FACTORY_VERSION} (${generatedBy}). Do not edit.`,
    ` * project: ${trace.project}  industry: ${trace.industry}`,
    ` * workflows: ${trace.workflows.join(", ")}`,
    " * Regenerate with: npm run factory -- generate-gas --project <path>",
    " */",
    "",
  ].join("\n");
}
