// Copy for /works/cafe: a lightweight demo, not a full case study.
// Generated by the same Factory pipeline as the Hair Salon demo
// (AI-Agent-Coconala-Factory/projects/2026/demo-cafe, layout grid-2x2-v1). All data is synthetic.

export const cafeDemo = {
  badge: "DEMO SAMPLE",
  eyebrow: "Cafe",
  title: "カフェ向け LINE予約受付デモ",
  titleLines: ["カフェ向け", "LINE予約受付デモ"],
  metaDescription:
    "カフェを想定した、LINE公式アカウントのリッチメニューから席の予約リクエスト・お問い合わせを受け付けるデモ構成。",
  description:
    "ヘアサロンのデモと同じ仕組みを、カフェ向けに組み替えたデモです。同じ大きさのボタンを2列×2段に並べた4ボタン構成です。予約はLINEで日時を選ぶ「予約リクエスト」として記録し、店舗側で確定します。",
  note: "実在の店舗ではなく、カフェを想定したデモです。店舗名・住所・連絡先はすべて架空のものです。",
  richMenu: {
    title: "Rich Menu",
    description:
      "「ご予約」「メニュー」「営業時間・アクセス」「お問い合わせ」を同じ大きさで並べた4ボタン構成。ボタンが大きく、どれも押しやすいレイアウトです。",
    image: {
      src: "/demos/cafe/rich-menu.png",
      width: 2500,
      height: 1686,
      alt: "カフェ向けリッチメニューのデモ画像（ご予約・メニュー・営業時間・アクセス・お問い合わせ）",
    },
  },
  workflow: {
    title: "Workflow",
    steps: [
      { label: "リッチメニュー", note: "「ご予約」をタップ" },
      { label: "日時の選択", note: "LINEの日時選択画面で希望日時を選ぶ" },
      { label: "Google Apps Script", note: "営業時間・受け入れ組数・既存の予約を確認" },
      { label: "スプレッドシート", note: "「REQUESTED（リクエスト）」として記録" },
      { label: "メール通知", note: "店舗へお知らせ" },
    ],
    note: "予約は確定ではなく「リクエスト」として記録されます。同じ時間帯に受け付ける組数（デモでは4組）と1組あたりの滞在時間（デモでは90分）は、スプレッドシートの設定で変えられます。",
  },
  buttons: {
    title: "4つのボタン",
    description: "それぞれのボタンを押すと、スプレッドシートの内容をもとにLINEで自動返信します。",
    items: [
      { name: "ご予約", detail: "日時選択画面を開き、予約リクエストとして記録" },
      { name: "メニュー", detail: "登録したメニューの名前・料金を返信" },
      { name: "営業時間・アクセス", detail: "住所・地図・営業時間・電話番号を返信" },
      { name: "お問い合わせ", detail: "送られたメッセージを記録し、店舗へメールでお知らせ" },
    ],
    note: "メニューの内容と料金は、お店ごとにスプレッドシートへ登録します。このデモにはメニューの登録例は含めていません。",
  },
  cta: {
    titleLines: ["同じ仕組みを、", "あなたのお店のLINEにも。"],
    buttonLabel: "Coconalaで相談する",
  },
};
