// Copy for /works/nail-salon: a lightweight demo, not a full case study.
// Generated by the same Factory pipeline as the Hair Salon demo
// (AI-Agent-Coconala-Factory/projects/2026/demo-nail-salon). All data is synthetic.

export const nailSalonDemo = {
  badge: "DEMO SAMPLE",
  eyebrow: "Nail Salon",
  title: "ネイルサロン向け LINE予約受付デモ",
  titleLines: ["ネイルサロン向け", "LINE予約受付デモ"],
  metaDescription:
    "ネイルサロンを想定した、LINE公式アカウントのリッチメニューから予約リクエスト・お問い合わせを受け付けるデモ構成。",
  description:
    "ヘアサロンのデモと同じ仕組みを、ネイルサロン向けの言葉・メニュー・デザインに置き換えたデモです。予約はLINEで日時を選ぶ「予約リクエスト」として記録し、店舗側で確定します。",
  note: "実在の店舗ではなく、ネイルサロンを想定したデモです。店舗名・料金・住所はすべて架空のものです。",
  richMenu: {
    title: "Rich Menu",
    description:
      "ご予約・ネイルメニュー・お問い合わせ・アクセス・営業時間・デザイン写真の6ボタン構成。ヘアサロンと同じレイアウトのまま、ラベルと配色だけをネイルサロン向けにしています。",
    image: {
      src: "/demos/nail-salon/rich-menu.png",
      width: 2500,
      height: 1686,
      alt: "ネイルサロン向けリッチメニューのデモ画像（ご予約・ネイルメニュー・お問い合わせ・アクセス・営業時間・デザイン写真）",
    },
  },
  workflow: {
    title: "Workflow",
    steps: [
      { label: "リッチメニュー", note: "「ご予約」をタップ" },
      { label: "日時の選択", note: "LINEの日時選択画面で希望日時を選ぶ" },
      { label: "Google Apps Script", note: "営業時間・空き状況を確認" },
      { label: "スプレッドシート", note: "「REQUESTED（リクエスト）」として記録" },
      { label: "メール通知", note: "店舗へお知らせ" },
    ],
    note: "予約は確定ではなく「リクエスト」として記録されます。ハンド／フットやデザインの内容は、受付後にLINEでご相談いただく流れです。",
  },
  menu: {
    title: "Menu（デモ用）",
    description: "「ネイルメニュー」ボタンでは、スプレッドシートに登録したメニューをLINEで返信します。以下はデモ用の架空のメニューです。",
    // Synthetic examples only: not real prices and not an actual salon's offering.
    items: [
      { name: "ワンカラー", minutes: 60, price: "5,500円" },
      { name: "グラデーション", minutes: 75, price: "6,600円" },
      { name: "フレンチ", minutes: 75, price: "6,600円" },
      { name: "定額デザイン", minutes: 90, price: "7,700円" },
      { name: "フットネイル（ワンカラー）", minutes: 75, price: "6,600円" },
      { name: "オフのみ", minutes: 30, price: "2,200円" },
    ],
    note: "料金・所要時間はデモ用の架空の値です。",
  },
  cta: {
    titleLines: ["同じ仕組みを、", "あなたのサロンのLINEにも。"],
    buttonLabel: "Coconalaで相談する",
  },
};
