// Copy for /works/restaurant: a lightweight demo, not a full case study.
// Generated by the same Factory pipeline as the Hair Salon demo
// (AI-Agent-Coconala-Factory/projects/2026/demo-restaurant, layout hero-1-plus-3-v1). All data is synthetic.

export const restaurantDemo = {
  badge: "DEMO SAMPLE",
  eyebrow: "Restaurant",
  title: "飲食店向け LINE席予約受付デモ",
  titleLines: ["飲食店向け", "LINE席予約受付デモ"],
  metaDescription:
    "飲食店を想定した、LINE公式アカウントのリッチメニューから席の予約リクエスト・お問い合わせを受け付けるデモ構成。",
  description:
    "ヘアサロンのデモと同じ仕組みを、飲食店向けに組み替えたデモです。上段に大きな「席のご予約」ボタン、下段に3つのボタンを並べた4ボタン構成です。予約はLINEで日時を選ぶ「予約リクエスト」として記録し、店舗側で確定します。",
  note: "実在の店舗ではなく、飲食店を想定したデモです。店舗名・住所・連絡先はすべて架空のものです。",
  richMenu: {
    title: "Rich Menu",
    description:
      "上段いっぱいの「席のご予約」と、下段の「お料理」「アクセス」「お問い合わせ」の4ボタン構成。いちばん押してほしい予約ボタンを大きくしています。",
    image: {
      src: "/demos/restaurant/rich-menu.png",
      width: 2500,
      height: 1686,
      alt: "飲食店向けリッチメニューのデモ画像（席のご予約・お料理・アクセス・お問い合わせ）",
    },
  },
  workflow: {
    title: "Workflow",
    steps: [
      { label: "リッチメニュー", note: "「席のご予約」をタップ" },
      { label: "日時の選択", note: "LINEの日時選択画面で希望日時を選ぶ" },
      { label: "Google Apps Script", note: "営業時間・受け入れ組数・既存の予約を確認" },
      { label: "スプレッドシート", note: "「REQUESTED（リクエスト）」として記録" },
      { label: "メール通知", note: "店舗へお知らせ" },
    ],
    note: "予約は確定ではなく「リクエスト」として記録されます。同じ時間帯に受け付ける組数（デモでは6組）と1組あたりの滞在時間（デモでは120分）は、スプレッドシートの設定で変えられます。人数や貸切・アレルギーのご相談は「お問い合わせ」から受け付けます。",
  },
  buttons: {
    title: "4つのボタン",
    description: "それぞれのボタンを押すと、スプレッドシートの内容をもとにLINEで自動返信します。",
    items: [
      { name: "席のご予約", detail: "日時選択画面を開き、予約リクエストとして記録" },
      { name: "お料理", detail: "登録したお料理・コースの名前・時間・料金を返信" },
      { name: "アクセス", detail: "住所・地図・営業時間・電話番号を返信" },
      { name: "お問い合わせ", detail: "送られたメッセージを記録し、店舗へメールでお知らせ" },
    ],
    note: "お料理・コースの内容と料金は、お店ごとにスプレッドシートへ登録します。このデモには料理の登録例は含めていません。",
  },
  cta: {
    titleLines: ["同じ仕組みを、", "あなたのお店のLINEにも。"],
    buttonLabel: "Coconalaで相談する",
  },
};
