// Copy for /works/spa: a lightweight demo, not a full case study.
// Generated by the same Factory pipeline as the Hair Salon demo
// (AI-Agent-Coconala-Factory/projects/2026/demo-spa). All data is synthetic.

export const spaDemo = {
  badge: "DEMO SAMPLE",
  eyebrow: "Spa",
  title: "スパ・リラクゼーション向け LINE予約受付デモ",
  titleLines: ["スパ・リラクゼーション向け", "LINE予約受付デモ"],
  metaDescription:
    "スパ・リラクゼーションサロンを想定した、LINE公式アカウントのリッチメニューから予約リクエスト・お問い合わせを受け付けるデモ構成。",
  description:
    "ヘアサロンのデモと同じ仕組みを、スパ向けの言葉・メニュー・落ち着いた配色に置き換えたデモです。予約はLINEで日時を選ぶ「予約リクエスト」として記録し、店舗側で確定します。",
  note: "実在の店舗ではなく、スパを想定したデモです。店舗名・料金・住所はすべて架空のものです。",
  richMenu: {
    title: "Rich Menu",
    description:
      "ご予約・メニュー・お問い合わせ・アクセス・営業時間・はじめての方の6ボタン構成。ヘアサロンと同じレイアウトのまま、ラベルと配色だけをスパ向けにしています。",
    image: {
      src: "/demos/spa/rich-menu.png",
      width: 2500,
      height: 1686,
      alt: "スパ向けリッチメニューのデモ画像（ご予約・メニュー・お問い合わせ・アクセス・営業時間・はじめての方）",
    },
  },
  workflow: {
    title: "Workflow",
    steps: [
      { label: "リッチメニュー", note: "「ご予約」をタップ" },
      { label: "日時の選択", note: "LINEの日時選択画面で希望日時を選ぶ" },
      { label: "Google Apps Script", note: "営業時間・空き状況を確認" },
      { label: "スプレッドシート", note: "「REQUESTED（リクエスト）」として記録" },
      { label: "メール通知", note: "店舗へお知らせ" },
    ],
    note: "予約は確定ではなく「リクエスト」として記録されます。コースやオプション、体調についてのご相談は、受付後にLINEでやり取りする流れです。",
  },
  menu: {
    title: "Menu（デモ用）",
    description: "「メニュー」ボタンでは、スプレッドシートに登録したコースをLINEで返信します。以下はデモ用の架空のメニューです。",
    // Synthetic examples only: not real prices and not an actual spa's offering.
    items: [
      { name: "アロマトリートメント", minutes: 60, price: "9,900円" },
      { name: "ボディケア", minutes: 60, price: "7,700円" },
      { name: "フェイシャル", minutes: 60, price: "8,800円" },
      { name: "リフレクソロジー", minutes: 45, price: "5,500円" },
      { name: "ヘッドスパ", minutes: 45, price: "6,600円" },
      { name: "アロマ＋ヘッドスパ", minutes: 90, price: "14,300円" },
    ],
    note: "料金・施術時間はデモ用の架空の値です。",
  },
  cta: {
    titleLines: ["同じ仕組みを、", "あなたのお店のLINEにも。"],
    buttonLabel: "Coconalaで相談する",
  },
};
