/*
 * GENERATED by AI-Agent-Coconala-Factory 0.1.0 (GAS Project Generator). Do not edit.
 * project: 2026/demo-restaurant  industry: restaurant
 * workflows: reservation-basic-v1@1.0.0, service-menu-v1@1.0.0, business-info-v1@1.0.0, inquiry-basic-v1@1.0.0
 * Regenerate with: npm run factory -- generate-gas --project <path>
 */
import { createEntrypoints } from "./entry";
import { CONFIG_SEED } from "./generated/configSeed";
import { MANIFEST } from "./generated/manifest";
import { API_ACTIONS, REGISTRY } from "./generated/registry";
import { RICH_MENU } from "./generated/richMenu";
import { LINE_ROUTES } from "./generated/routes";
import { SCHEMA } from "./generated/schema";

const entry = createEntrypoints({ schema: SCHEMA, registry: REGISTRY, apiActions: API_ACTIONS, routes: LINE_ROUTES, configSeed: CONFIG_SEED, richMenu: RICH_MENU, manifest: MANIFEST });

// esbuild wraps everything in an IIFE, so expose the entry points on the real global object under
// prefixed names. The top-level wrappers appended by esbuild.config.mjs forward to these.
const g = globalThis as unknown as Record<string, unknown>;
g.__factory_doGet = entry.doGet;
g.__factory_doPost = entry.doPost;
g.__factory_setupSpreadsheet = entry.setupSpreadsheet;
g.__factory_setupRichMenu = entry.setupRichMenu;
