/*
 * GENERATED by AI-Agent-Coconala-Factory 0.1.0 (GAS Project Generator). Do not edit.
 * project: 2026/demo-hair-salon  industry: hair_salon
 * workflows: reservation-basic-v1@1.0.0, service-menu-v1@1.0.0, inquiry-basic-v1@1.0.0, business-info-v1@1.0.0
 * Regenerate with: npm run factory -- generate-gas --project <path>
 */
import { describe, expect, it } from "vitest";
import { findRoute, handleLineWebhook, parsePostbackData } from "../src/line/webhook";
import { CONFIG_SEED } from "../src/generated/configSeed";
import { API_ACTIONS, REGISTRY } from "../src/generated/registry";
import { RICH_MENU } from "../src/generated/richMenu";
import { LINE_ROUTES } from "../src/generated/routes";
import { SCHEMA } from "../src/generated/schema";
import { makeContext } from "./support/fakes";

describe("generated wiring", () => {
  it("registers every handler under its own id", () => {
    for (const [id, handler] of Object.entries(REGISTRY)) expect(handler.id).toBe(id);
  });

  it("routes every LINE entry to a LINE-enabled handler", () => {
    for (const route of LINE_ROUTES) {
      expect(REGISTRY[route.action], route.action).toBeDefined();
      expect(REGISTRY[route.action].fromLine, route.action).toBeTypeOf("function");
      if (route.mode === "awaitText") expect(route.prompt).toBeTruthy();
    }
  });

  it("exposes only registered actions on the API", () => {
    for (const id of API_ACTIONS) expect(REGISTRY[id]).toBeDefined();
  });

  it("only sends postbacks that the webhook can route", () => {
    for (const area of RICH_MENU.areas) {
      const action = area.action as { type: string; data?: string; uri?: string };
      if (action.type === "uri") {
        expect(action.uri).toMatch(/^https:\/\//);
        continue;
      }
      expect(findRoute(LINE_ROUTES, parsePostbackData(action.data ?? "")), action.data).toBeDefined();
    }
  });

  it("seeds only CONFIG keys the schema declares", () => {
    const declared = SCHEMA.configKeys.map((k) => k.key);
    for (const key of Object.keys(CONFIG_SEED)) expect(declared).toContain(key);
  });

  it("answers every rich menu button in an in-memory smoke run", () => {
    const config: Record<string, string> = {};
    for (const key of SCHEMA.configKeys) if (key.default !== undefined) config[key.key] = key.default;
    Object.assign(config, CONFIG_SEED);
    const ctx = makeContext({ schema: SCHEMA, config });
    RICH_MENU.areas.forEach((area, index) => {
      const action = area.action as { type: string; data?: string };
      if (action.type === "uri") return;
      const userId = `U0000smoke${index}`;
      handleLineWebhook(
        { events: [{ type: "postback", webhookEventId: `smoke-${index}`, replyToken: `rt-${index}`, source: { userId }, postback: { data: action.data, params: { datetime: "2099-01-01T10:00" } } }] },
        { routes: LINE_ROUTES, registry: REGISTRY, ctx },
      );
      const route = findRoute(LINE_ROUTES, parsePostbackData(action.data ?? ""))!;
      if (route.mode === "awaitText") {
        handleLineWebhook(
          { events: [{ type: "message", webhookEventId: `smoke-text-${index}`, replyToken: `rt-text-${index}`, source: { userId }, message: { type: "text", text: "テスト送信です" } }] },
          { routes: LINE_ROUTES, registry: REGISTRY, ctx },
        );
      }
    });
    const buttons = RICH_MENU.areas.filter((a) => (a.action as { type: string }).type !== "uri").length;
    expect(ctx.replies.length).toBeGreaterThanOrEqual(buttons);
    expect(ctx.errors.filter((e) => e.event === "line.unroutable")).toEqual([]);
  });
});
