/*
 * GENERATED by AI-Agent-Coconala-Factory 0.1.0 (GAS Project Generator). Do not edit.
 * project: 2026/demo-nail-salon  industry: nail_salon
 * workflows: reservation-basic-v1@1.0.0, service-menu-v1@1.0.0, inquiry-basic-v1@1.0.0, business-info-v1@1.0.0
 * Regenerate with: npm run factory -- generate-gas --project <path>
 */
import { describe, expect, it } from "vitest";
import { handleLineWebhook, LineRoute } from "../src/line/webhook";
import { ERROR_MESSAGES_JA } from "../src/lib/result";
import { CONFIG_SEED } from "../src/generated/configSeed";
import { REGISTRY } from "../src/generated/registry";
import { LINE_ROUTES } from "../src/generated/routes";
import { SCHEMA } from "../src/generated/schema";
import { makeContext, TestContext } from "./support/fakes";

const USER = "U0000runtime";
const SAFE_MESSAGES = Object.values(ERROR_MESSAGES_JA);

function seededConfig(): Record<string, string> {
  const config: Record<string, string> = {};
  for (const key of SCHEMA.configKeys) if (key.default !== undefined) config[key.key] = key.default;
  return { ...config, ...CONFIG_SEED };
}

const counts = (ctx: TestContext) => Object.fromEntries(SCHEMA.sheets.filter((s) => ctx.tables.hasSheet(s.name)).map((s) => [s.name, ctx.tables.readAll(s.name).length]));
const data = (route: LineRoute) => `wf=${route.workflowId}&e=${route.entry}`;

/** One customer interaction for a route. Returns the id of the event that runs the action. */
function deliver(ctx: TestContext, route: LineRoute, id: string, input: { text?: string; datetime?: string }): string {
  const postback = { type: "postback", webhookEventId: `${id}-pb`, replyToken: `rt-${id}-pb`, source: { userId: USER }, postback: { data: data(route), params: (input.datetime ? { datetime: input.datetime } : {}) as Record<string, string> } };
  handleLineWebhook({ events: [postback] }, { routes: LINE_ROUTES, registry: REGISTRY, ctx });
  if (route.mode !== "awaitText") return postback.webhookEventId;
  const message = { type: "message", webhookEventId: `${id}-msg`, replyToken: `rt-${id}-msg`, source: { userId: USER }, message: { type: "text", text: input.text ?? "" } };
  handleLineWebhook({ events: [message] }, { routes: LINE_ROUTES, registry: REGISTRY, ctx });
  return message.webhookEventId;
}

/** A datetime the project's own CONFIG accepts (first open slot in the next weeks), found by asking the runtime. */
function acceptedDatetime(route: LineRoute): string | undefined {
  for (let day = 2; day <= 28; day++) {
    for (let hour = 6; hour <= 22; hour++) {
      const time = `${String(hour).padStart(2, "0")}:00`;
      const date = new Date(Date.UTC(2026, 9, 1 + day)).toISOString().slice(0, 10);
      const ctx = makeContext({ schema: SCHEMA, config: seededConfig() });
      const before = counts(ctx);
      deliver(ctx, route, "probe", { datetime: `${date}T${time}` });
      if (JSON.stringify(counts(ctx)) !== JSON.stringify(before)) return `${date}T${time}`;
    }
  }
  return undefined;
}

const accepted = new Map<LineRoute, string | undefined>();

function validInput(route: LineRoute): { text?: string; datetime?: string } {
  if (route.mode === "awaitText") return { text: "テスト送信です（自動テスト）" };
  if (!accepted.has(route)) accepted.set(route, acceptedDatetime(route));
  return { datetime: accepted.get(route) ?? "2026-10-05T11:00" };
}

describe.each(LINE_ROUTES.map((route) => [`${route.workflowId}#${route.entry}`, route] as const))("LINE runtime %s", (_name, route) => {
  it("valid input: replies and logs no error", () => {
    const ctx = makeContext({ schema: SCHEMA, config: seededConfig() });
    deliver(ctx, route, "valid", validInput(route));
    expect(ctx.replies.length).toBeGreaterThan(0);
    expect(ctx.errors).toEqual([]);
    for (const reply of ctx.replies) for (const message of reply.messages) expect(SAFE_MESSAGES).not.toContain(message.text);
  });

  it("duplicate webhook event: no second record and no second reply", () => {
    const ctx = makeContext({ schema: SCHEMA, config: seededConfig() });
    const input = validInput(route);
    deliver(ctx, route, "dup", input);
    const [rows, replies] = [counts(ctx), ctx.replies.length];
    deliver(ctx, route, "dup", input);
    expect(counts(ctx)).toEqual(rows);
    expect(ctx.replies.length).toBe(replies);
  });

  it("invalid input: a safe reply and no new record", () => {
    const ctx = makeContext({ schema: SCHEMA, config: seededConfig() });
    const before = counts(ctx);
    const invalid = route.mode === "awaitText" ? { text: "あ".repeat(6000) } : { datetime: "not-a-date" };
    deliver(ctx, route, "invalid", invalid);
    expect(counts(ctx)).toEqual(before);
    expect(ctx.replies.length).toBeGreaterThan(0);
    for (const reply of ctx.replies) for (const message of reply.messages) expect(message.text).not.toMatch(/Error|sheet|undefined|stack/i);
  });

  it("broken spreadsheet: only the fixed safe message reaches the customer", () => {
    const ctx = makeContext({ schema: SCHEMA, config: {}, omitSheets: SCHEMA.sheets.map((s) => s.name) });
    deliver(ctx, route, "broken", validInput(route));
    const last = ctx.replies[ctx.replies.length - 1];
    expect(SAFE_MESSAGES).toContain(last.messages[0].text);
    expect(ctx.errors.map((e) => e.event)).toContain("line.action_failed");
  });
});

describe("LINE runtime: unknown input", () => {
  it("ignores postbacks for unknown workflows or entries", () => {
    const ctx = makeContext({ schema: SCHEMA, config: seededConfig() });
    const sent = handleLineWebhook(
      { events: [{ type: "postback", webhookEventId: "u1", replyToken: "r1", source: { userId: USER }, postback: { data: "wf=unknown-v1&e=default" } }, { type: "postback", webhookEventId: "u2", replyToken: "r2", source: { userId: USER }, postback: { data: `wf=${LINE_ROUTES[0].workflowId}&e=no-such-entry` } }] },
      { routes: LINE_ROUTES, registry: REGISTRY, ctx },
    );
    expect(sent).toEqual([]);
  });

  it("answers an unregistered action with the safe UNKNOWN_ACTION message", () => {
    const ctx = makeContext({ schema: SCHEMA, config: seededConfig() });
    const routes: LineRoute[] = [{ workflowId: "ghost-v1", entry: "default", action: "noSuchAction", mode: "direct" }];
    const sent = handleLineWebhook({ events: [{ type: "postback", webhookEventId: "g1", replyToken: "rg", source: { userId: USER }, postback: { data: "wf=ghost-v1&e=default" } }] }, { routes, registry: REGISTRY, ctx });
    expect(sent[0].messages[0].text).toBe(ERROR_MESSAGES_JA.UNKNOWN_ACTION);
  });
});
